#!/bin/bash
# Delete branches tracking a contrib-* remote

source $(readlink -f ${BASH_SOURCE[0]} | xargs dirname)/common.sh

for LINE in $(git for-each-ref --format="%(refname:short):%(upstream:short)" refs/heads/ | grep -E ':contrib-[^/]+/.+$')
do
	LOCAL_BRANCH=$(echo "$LINE" | cut -d':' -f 1)
	UPSTREAM_BRANCH=$(echo "$LINE" | cut -d':' -f 2)
	echo "Branch '$LOCAL_BRANCH' is tracking the remote branch '$UPSTREAM_BRANCH', which is on a contributor's remote. Deleting."
	git branch -D "$LOCAL_BRANCH"
done
