#!/bin/bash
# List branches that are not synchronized with their remote tracking branch

source $(readlink -f ${BASH_SOURCE[0]} | xargs dirname)/lib/common.sh

git fetch --all --prune

git for-each-ref --format='%(refname:short) %(push:short) %(push:track)' refs/heads | sed -r 's/^(\S+)  $/\1  [no upstream]/' | grep --color=no -E '^\S+ \S* \[' \
	|| log "No unsynchronized branch."
