#!/bin/bash

source $(readlink -f ${BASH_SOURCE[0]} | xargs dirname)/lib/common.sh

BRANCH="${1}"
NEW="${2}"
CURRENT=$(git rev-parse "$BRANCH")

git update-ref "refs/heads/$BRANCH" "$NEW" "$CURRENT"

success "Successfully reset branch '$BRANCH' to '$NEW'."
