#!/bin/bash

source $(readlink -f ${BASH_SOURCE[0]} | xargs dirname)/common.sh

if [ "$1" = 'setup' ]
then
	shift
	git config --local 'ci.test.remote' "$1"
	success "Successfully set the remote to push to for tests to '$1'."
fi

REMOTE=$(git config --local 'ci.test.remote')

[ -n "$REMOTE" ] || abort "Use 'git test setup <remote>' to set the remote to push to first."

COMMIT=$(git rev-parse ${1:-HEAD})

BRANCH=$(git config 'ci.test.branch')
[ -n "$BRANCH" ] || abort 'Internal error: the test branch has not been set up.'

git update-ref "refs/heads/$BRANCH" "$COMMIT"
git push --force "$REMOTE" "$BRANCH":"$BRANCH"
