#!/bin/bash
# Various utilities around GitHub forks

source $(readlink -f ${BASH_SOURCE[0]} | xargs dirname)/lib/common.sh

function usage() {
	log "Usage:"
	log -e "\tgit fork setup <upstream-remote> <fork-remote>"
	log -e "OR"
	log -e "\tgit fork purge"
	log -e "OR"
	log -e "\tgit fork get upstream.remote"
	log -e "OR"
	log -e "\tgit fork get upstream.url.http"
	log -e "OR"
	log -e "\tgit fork get upstream.branch.head.relative"
	log -e "OR"
	log -e "\tgit fork get upstream.repository.name"
	log -e "OR"
	log -e "\tgit fork get remote"
	log -e "OR"
	log -e "\tgit fork get user.name"
	log -e "OR"
	log -e "\tgit fork branch init"
	abort
}

function convert_legacy() {
	LEGACY_VALUE=$(git config --local "$1") \
		&& log "Moving legacy configuration option '$1' to '$2'..." \
		&& git config --local "$2" "$LEGACY_VALUE" \
		&& git config --local --unset "$1" \
		&& echo "$LEGACY_VALUE"
}

if [ "$1" = 'setup' ]
then
	shift
	(( $# == 2 )) && [ -n "$1" -a -n "$2" ] || usage
	git config --local fork.upstream.remote "$1"
	git config --local fork.remote "$2"
	success "Successfully set the upstream remote ('$1') and the fork remote ('$2')."
elif [ "$1" = 'purge' ]
then
	shift
	(( $# == 0 )) || usage
	git config --local --unset fork.upstream.remote || true
	git config --local --unset fork.remote || true
	git config --local --unset sync.fork.remote || true
	git config --local --unset sync.fork.upstream.remote || true
	success "Successfully removed all configuration for 'git-fork'."
fi

UPSTREAM_REMOTE=$(git config --local fork.upstream.remote \
	|| convert_legacy sync.fork.upstream.remote fork.upstream.remote) \
	|| abort "Use 'git fork setup <upstream-remote> <fork-remote>' first."
FORK_REMOTE=$(git config --local fork.remote \
	|| convert_legacy sync.fork.remote fork.remote) \
	|| abort "Use 'git fork setup <upstream-remote> <fork-remote>' first."

if [ "$1" = 'get' ]
then
	shift
elif [ "$1" = 'branch' ]
then
	shift
	if [ "$1" = 'init' ]
	then
		git push -u "$FORK_REMOTE" $(git rev-parse --abbrev-ref HEAD)
		success
	else
		usage
	fi
else
	usage
fi

if [ "$1" = 'upstream.remote' ]
then
	shift
	(( $# == 0 )) || usage
	echo "$UPSTREAM_REMOTE"
elif [ "$1" = 'upstream.url.http' ]
then
	shift
	(( $# == 0 )) || usage
	git remote get-url "$UPSTREAM_REMOTE" | sed -r 's,^git@github.com:(.*)\.git$,https://github.com/\1,'
elif [ "$1" = 'upstream.branch.head' ]
then
	shift
	(( $# == 0 )) || usage
	if ! UPSTREAM_HEAD=$(git rev-parse --abbrev-ref "$UPSTREAM_REMOTE/HEAD" 2>/dev/null)
	then
		# Maybe the upstream HEAD was not set yet, try to set it automatically
		git remote set-head -a "$UPSTREAM_REMOTE" 1>&2
		UPSTREAM_HEAD=$(git rev-parse --abbrev-ref "$UPSTREAM_REMOTE/HEAD")
	fi
	echo $UPSTREAM_HEAD
elif [ "$1" = 'upstream.branch.head.relative' ]
then
	shift
	(( $# == 0 )) || usage
	"$0" get 'upstream.branch.head' | sed -r "s,^$UPSTREAM_REMOTE/,,"
elif [ "$1" = 'upstream.repository.name' ]
then
	shift
	(( $# == 0 )) || usage
	git remote get-url "$UPSTREAM_REMOTE" | sed -r 's,^.*/(.*)\.git$,\1,'
elif [ "$1" = 'remote' ]
then
	shift
	(( $# == 0 )) || usage
	echo "$FORK_REMOTE"
elif [ "$1" = 'user.name' ]
then
	shift
	(( $# == 0 )) || usage
	git remote get-url "$FORK_REMOTE" | sed -r 's,^git@github.com:([^/]+)/.*\.git$,\1,;s,^https://github.com/([^/]+)/.*$,\1,'
else
	usage
fi

